import { Product } from "./types";

export const seedProducts: Product[] = [
  {
    id: "oak-haven-sofa",
    name: "Oak Haven Modular Sofa",
    category: "Sofas",
    description: "Deep, structured seating with stain-resistant woven upholstery and a low modern profile.",
    details: "Designed for everyday family use while keeping a showroom silhouette. The modular shape lets customers adapt it to apartments, lounges, and open living rooms.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=85",
    supplierCost: 790,
    price: 930,
    stock: 14,
    materials: "Performance fabric, kiln-dried frame",
    dimensions: "286 x 96 x 74 cm",
    room: "Living room",
    trendScore: 94,
    visits: 72,
    likes: 28,
    bought: 9
  },
  {
    id: "linen-arc-lounge-chair",
    name: "Linen Arc Lounge Chair",
    category: "Chairs",
    description: "Curved accent chair with a compact footprint, ideal for reading corners and hospitality spaces.",
    details: "A high-margin accent piece with strong impulse-buy appeal. Works well in pairs and photographs beautifully for social ads.",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1400&q=85",
    supplierCost: 260,
    price: 390,
    stock: 23,
    materials: "Textured linen blend, ash legs",
    dimensions: "82 x 78 x 83 cm",
    room: "Bedroom / Living",
    trendScore: 88,
    visits: 54,
    likes: 34,
    bought: 7
  },
  {
    id: "nord-dining-table",
    name: "Nord Extendable Dining Table",
    category: "Tables",
    description: "Warm oak dining table with a hidden extension leaf for six to eight seats.",
    details: "The table targets customers moving into larger homes and buyers replacing temporary furniture with durable long-term pieces.",
    image: "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1400&q=85",
    supplierCost: 620,
    price: 760,
    stock: 11,
    materials: "Oak veneer, solid beech supports",
    dimensions: "180-230 x 90 x 76 cm",
    room: "Dining room",
    trendScore: 91,
    visits: 63,
    likes: 21,
    bought: 6
  },
  {
    id: "marlow-storage-bed",
    name: "Marlow Storage Bed",
    category: "Beds",
    description: "Upholstered king bed with lift-up storage and a slim cushioned headboard.",
    details: "High perceived value and practical storage make this a strong recommendation for urban apartments and premium rentals.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=85",
    supplierCost: 740,
    price: 890,
    stock: 9,
    materials: "Boucle fabric, metal lift mechanism",
    dimensions: "168 x 214 x 108 cm",
    room: "Bedroom",
    trendScore: 86,
    visits: 45,
    likes: 19,
    bought: 5
  },
  {
    id: "atelier-work-desk",
    name: "Atelier Work Desk",
    category: "Desks",
    description: "Minimal desk with cable routing, soft-close drawer, and a balanced home-office footprint.",
    details: "Built for hybrid workers who want a real desk that still belongs in a designed home.",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1400&q=85",
    supplierCost: 310,
    price: 430,
    stock: 18,
    materials: "Walnut veneer, powder-coated steel",
    dimensions: "130 x 62 x 76 cm",
    room: "Office",
    trendScore: 83,
    visits: 38,
    likes: 14,
    bought: 4
  },
  {
    id: "solace-media-console",
    name: "Solace Media Console",
    category: "Storage",
    description: "Low media unit with ribbed doors, concealed cable paths, and generous interior storage.",
    details: "A strong cross-sell for sofa buyers and one of the safest categories for reliable margin.",
    image: "https://images.unsplash.com/photo-1615529162924-f8605388461d?auto=format&fit=crop&w=1400&q=85",
    supplierCost: 390,
    price: 520,
    stock: 16,
    materials: "Engineered oak, soft-close hinges",
    dimensions: "180 x 42 x 52 cm",
    room: "Living room",
    trendScore: 89,
    visits: 58,
    likes: 26,
    bought: 8
  }
];
